/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesRouteImport } from './routes/_pages'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as PagesAboutRouteImport } from './routes/_pages/about'
import { Route as PagesBrandRouteImport } from './routes/_pages/brand'
import { Route as PagesContactRouteImport } from './routes/_pages/contact'
import { Route as PagesDpaRouteImport } from './routes/_pages/dpa'
import { Route as PagesPrivacyRouteImport } from './routes/_pages/privacy'
import { Route as PagesRefundsRouteImport } from './routes/_pages/refunds'
import { Route as PagesTermsRouteImport } from './routes/_pages/terms'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhookPolarRouteImport } from './routes/api/webhook/polar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/_pages',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAboutRoute = PagesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PagesRoute,
} as any)
const PagesBrandRoute = PagesBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => PagesRoute,
} as any)
const PagesContactRoute = PagesContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PagesRoute,
} as any)
const PagesDpaRoute = PagesDpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => PagesRoute,
} as any)
const PagesPrivacyRoute = PagesPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PagesRoute,
} as any)
const PagesRefundsRoute = PagesRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => PagesRoute,
} as any)
const PagesTermsRoute = PagesTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PagesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookPolarRoute = ApiWebhookPolarRouteImport.update({
  id: '/api/webhook/polar',
  path: '/api/webhook/polar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/welcome': typeof WelcomeRoute
  '/about': typeof PagesAboutRoute
  '/brand': typeof PagesBrandRoute
  '/contact': typeof PagesContactRoute
  '/dpa': typeof PagesDpaRoute
  '/privacy': typeof PagesPrivacyRoute
  '/refunds': typeof PagesRefundsRoute
  '/terms': typeof PagesTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/welcome': typeof WelcomeRoute
  '/about': typeof PagesAboutRoute
  '/brand': typeof PagesBrandRoute
  '/contact': typeof PagesContactRoute
  '/dpa': typeof PagesDpaRoute
  '/privacy': typeof PagesPrivacyRoute
  '/refunds': typeof PagesRefundsRoute
  '/terms': typeof PagesTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pages': typeof PagesRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/welcome': typeof WelcomeRoute
  '/_pages/about': typeof PagesAboutRoute
  '/_pages/brand': typeof PagesBrandRoute
  '/_pages/contact': typeof PagesContactRoute
  '/_pages/dpa': typeof PagesDpaRoute
  '/_pages/privacy': typeof PagesPrivacyRoute
  '/_pages/refunds': typeof PagesRefundsRoute
  '/_pages/terms': typeof PagesTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/sign-in'
    | '/welcome'
    | '/about'
    | '/brand'
    | '/contact'
    | '/dpa'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/api/auth/$'
    | '/api/webhook/polar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/sign-in'
    | '/welcome'
    | '/about'
    | '/brand'
    | '/contact'
    | '/dpa'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/api/auth/$'
    | '/api/webhook/polar'
  id:
    | '__root__'
    | '/'
    | '/_pages'
    | '/checkout'
    | '/dashboard'
    | '/sign-in'
    | '/welcome'
    | '/_pages/about'
    | '/_pages/brand'
    | '/_pages/contact'
    | '/_pages/dpa'
    | '/_pages/privacy'
    | '/_pages/refunds'
    | '/_pages/terms'
    | '/api/auth/$'
    | '/api/webhook/polar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesRoute: typeof PagesRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  SignInRoute: typeof SignInRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhookPolarRoute: typeof ApiWebhookPolarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/about': {
      id: '/_pages/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PagesAboutRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/brand': {
      id: '/_pages/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof PagesBrandRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/contact': {
      id: '/_pages/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PagesContactRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/dpa': {
      id: '/_pages/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof PagesDpaRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/privacy': {
      id: '/_pages/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PagesPrivacyRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/refunds': {
      id: '/_pages/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof PagesRefundsRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/terms': {
      id: '/_pages/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PagesTermsRouteImport
      parentRoute: typeof PagesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/polar': {
      id: '/api/webhook/polar'
      path: '/api/webhook/polar'
      fullPath: '/api/webhook/polar'
      preLoaderRoute: typeof ApiWebhookPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PagesRouteChildren {
  PagesAboutRoute: typeof PagesAboutRoute
  PagesBrandRoute: typeof PagesBrandRoute
  PagesContactRoute: typeof PagesContactRoute
  PagesDpaRoute: typeof PagesDpaRoute
  PagesPrivacyRoute: typeof PagesPrivacyRoute
  PagesRefundsRoute: typeof PagesRefundsRoute
  PagesTermsRoute: typeof PagesTermsRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesAboutRoute: PagesAboutRoute,
  PagesBrandRoute: PagesBrandRoute,
  PagesContactRoute: PagesContactRoute,
  PagesDpaRoute: PagesDpaRoute,
  PagesPrivacyRoute: PagesPrivacyRoute,
  PagesRefundsRoute: PagesRefundsRoute,
  PagesTermsRoute: PagesTermsRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesRoute: PagesRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  SignInRoute: SignInRoute,
  WelcomeRoute: WelcomeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhookPolarRoute: ApiWebhookPolarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
