/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhookPolarRouteImport } from './routes/api/webhook/polar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookPolarRoute = ApiWebhookPolarRouteImport.update({
  id: '/api/webhook/polar',
  path: '/api/webhook/polar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/webhook/polar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/webhook/polar'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/webhook/polar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  SignInRoute: typeof SignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhookPolarRoute: typeof ApiWebhookPolarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/polar': {
      id: '/api/webhook/polar'
      path: '/api/webhook/polar'
      fullPath: '/api/webhook/polar'
      preLoaderRoute: typeof ApiWebhookPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  SignInRoute: SignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhookPolarRoute: ApiWebhookPolarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
